### ISSUE TITLE
Rename the GitHub action filename to `tests`, `tests-coverage` or `jest-coverage`

### ISSUE THREAD

**Issue by stemount** [red-perfume/red-perfume#28]
Linked to PR #27, `node.js.yml` could be renamed to make it obvious that this is the test / Jest coverage

**Comment by TheJaredWilcurt** [comment]
I'm open to renaming it from `node.js.yml` to something more specific, so long as it isn't too specific.

The file handles the following things:

* Linting via ESLint
* Running unit tests via Jest
* Creating a test coverage badge for the branch
* Eventually, it will also test on the oldest supported version of Node.

Thoughts on names:

* `ci.yml` - less specific, completely generic
* `node.js.yml` - more specifc, explains that all Actions are ran with node
* `jest-coverage.yml` - too specific, not only does it show the coverage it also runs the tests, and linting.
* `tests-coverage.yml` - less specific (doesn't mention jest), jest is the only testing tool currently used. also too specific
* `tests` - too specific, the actions also do linting.

**Comment by stemount** [comment]
@TheJaredWilcurt I vote `tests-lint-coverage.yml`. I *assume* that workflows allows child folders e.g. `.github/workflows/tests/lint-coverage.yml` so tests can actually be it's own folder!

🙌🏻
